#!/bin/bash
MY_IP=$(hostname -i | sed -nr 's/([0-9.]+).*/\1/p')

export HUB_API_ADDRESS=${HUB_API_ADDRESS=${MY_IP}}
export HUB_API_PORT=${HUB_API_PORT=8001}

export HUB_CONNECT_ADDRESS=${HUB_CONNECT_ADDRESS=${MY_IP}}
export HUB_CONNECT_PORT=${HUB_CONNECT_PORT=${HUB_API_PORT}}

export HUB_PROXY_ADDRESS=${HUB_PROXY_ADDRESS="0.0.0.0"}
export HUB_PROXY_PORT=${HUB_PROXY_PORT=80}
export HUB_SSL_KEY=${HUB_SSL_KEY=""}
export HUB_SSL_CERT=${HUB_SSL_CERT=""}

export HUB_DB_URI=${HUB_DB_URI="sqlite:///jupyterhub.sqlite"}
export HUB_DB_OPTS=${HUB_DB_OPTS=""}

export JUPYTER_NOTEBOOK_DIR=${JUPYTER_NOTEBOOK_DIR="/srv/notebooks"}
export JUPYTER_NOTEBOOK_VOLUME=${JUPYTER_NOTEBOOK_VOLUME=""}

export JUPYTER_DOCKER_COMMAND=${JUPYTER_DOCKER_COMMAND="jupyterhub-singleuser"}
export JUPYTER_DOCKER_IMAGE=${JUPYTER_DOCKER_IMAGE="dimajix/jupyterhub:4.3.30"}
export JUPYTER_DOCKER_NETWORK=${JUPYTER_DOCKER_NETWORK="bridge"}
export JUPYTER_DOCKER_VOLUME_DRIVER=${JUPYTER_DOCKER_VOLUME_DRIVER="local"}
export JUPYTER_DOCKER_VOLUMES=${JUPYTER_DOCKER_VOLUMES=""}

export LDAP_SERVER_ADDRESS=${LDAP_SERVER_ADDRESS}
export LDAP_SERVER_PORT=${LDAP_SERVER_PORT=389}
export LDAP_SERVER_SSL=${LDAP_SERVER_SSL="False"}
export LDAP_USER_TEMPLATE=${LDAP_USER_TEMPLATE}
export LDAP_USER_GROUP=${LDAP_USER_GROUP}
